[versions]
org-jetbrains-kotlin = "1.9.20"
org-jetbrains-kotlinx = "1.3.8"

[libraries]
logback-classic = "ch.qos.logback:logback-classic:1.2.3"
jackson-bom = "com.fasterxml.jackson:jackson-bom:2.16.1"
clikt = "com.github.ajalt:clikt:2.4.0"
consoleui = "de.codeshelf.consoleui:consoleui:0.0.13"
slf4j-api = "org.slf4j:slf4j-api:1.7.30"

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "org-jetbrains-kotlinx" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "org-jetbrains-kotlinx" }
junit-jupiter = "org.junit.jupiter:junit-jupiter:5.6.3"

[plugins]
ben-manes-versions = "com.github.ben-manes.versions:0.50.0"
version-catalog-update = "nl.littlerobots.version-catalog-update:0.8.3"
kotlin-jvm = "org.jetbrains.kotlin.jvm:1.9.20"
